# Generated by Django 5.2 on 2025-04-26 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('types', models.JSONField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('abilities', models.JSONField()),
                ('base_experience', models.IntegerField()),
                ('stats', models.JSONField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('level', models.IntegerField(default=5)),
                ('experience', models.IntegerField(default=0)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('legendary', 'Legendary'), ('custom', 'Custom')], default='common', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('acquired_date', models.DateTimeField(auto_now_add=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('image_url', models.URLField(blank=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemonspecies')),
            ],
        ),
    ]
